#!/usr/local/bin/python

import os
import os.path
import sys
from subprocess import call, Popen, STDOUT, PIPE

host = os.path.basename(sys.argv[0]).split('_')[1]
#command = '/usr/local/bin/snmpwalk -c public -v1 %s .1.3.6.1.4.1.14988.1.1.1.1.1.4' % host
command = '/usr/local/bin/curl -s http://ubnt:ubnt@%s/signal.cgi' % host

if sys.argv[-1] == "config":
    print "host_name", host
    print "graph_title Wireless Interface signal strength"
    print 'graph_vlabel RSSI (dBm)'
    # print 'graph_args --lower-limit 0'
    print 'graph_category Network'
    #print 'graph_info This graph shows the percentage of printer consumables used.'
        
    print "signal.label RSSI (dBm)"
    print "noise.label noise (dBm)"

p =  Popen(command,
           shell=True,
           stdout=PIPE,
           stderr=STDOUT)

# signal=-64; noisef=-95;
data =  p.stdout.read()
signal, noise = data.split(';')[:2]
signal = signal.strip(' signal=')
noise = noise.strip(' noisef=')
print "signal.value", signal
print "noise.value", noise
        
