#!/usr/local/bin/python

import os
import os.path
import sys
from subprocess import call, Popen, STDOUT, PIPE

host = os.path.basename(sys.argv[0]).split('_')[-1]
command = '/usr/local/bin/snmpwalk -c public -v1 %s .1.3.6.1.4.1.14988.1.1.1.1.1.4' % host


if sys.argv[-1] == "config":
    print "graph_title Interface wifi0 signal strength"
    print 'graph_vlabel RSSI (dBm)'
    # print 'graph_args --lower-limit 0'
    print 'graph_category Network'
    #print 'graph_info This graph shows the percentage of printer consumables used.'
        
    print "signal.label RSSI (dBm)"

p =  Popen(command,
           shell=True,
           stdout=PIPE,
           stderr=STDOUT)

print "signal.value",
print p.stdout.read().split('=')[-1].strip()
        
